### ISSUE TITLE
Support perconaOptions per change

### ISSUE THREAD

**Issue by CyrilDevOps** [liquibase/liquibase-percona#57]
... same as the usePercona: true

We would like to be able to 'overwrite' the percona options on specific changeset.
We use liquibase on multiple schema and multiple tables, they may not all need the same percona.options
as they have differents load or requirements.

**Comment by adangel** [comment]
Let me repeat, so that I'm sure, I understand you correctly: Basically, you want to be able to specify the options, you can currently specify via the [system property](https://github.com/liquibase/liquibase-percona#system-properties) "`liquibase.percona.options`" for each changeset individually. The system property currently applies for all changes/changesets that are executed in the same run.

E.g. you'd like to have such a changeset:

```xml
<addColumn tableName="person"
    xmlns:liquibasePercona="http://github.com/liquibase/liquibase-percona"
    liquibasePercona:perconaOptions="--alter-foreign-keys-method=auto --nocheck-unique-key-change">
    <column name="address" type="varchar(255)"/>
</addColumn>
```

or for yaml

```yaml
- changeSet:
    id: 2
    author: Alice
    changes:
      - addColumn:
          tableName: person
          perconaOptions: "--alter-foreign-keys-method=auto --nocheck-unique-key-change"
          columns:
            - column:
                name: address
                type: varchar(255)
```

That sounds doable. The relationship to the system property will be: If you specify the perconaOptions at an individual changeset, then the system property is ignored. The system property would then only serve the default options if no other options are specified at the changeset.
