### ISSUE TITLE
Support usePercona on SQL change type

### ISSUE THREAD

**Issue by nholmes3** [liquibase/liquibase-percona#80]
See #291 for usage examples.

----

See [SQL Change Type](https://docs.liquibase.com/change-types/sql.html)

Are there any plans to add the custom SQL change type to the list of supported changes for use with percona?

Something like:

```
databaseChangeLog:
- changeSet:
    id: convert-charset
    author: nholmes
    changes:
    - sql:
        usePercona: true
        splitStatements: true
        sql: |
            ALTER TABLE {table} CONVERT TO CHARACTER SET utf8mb4;

```

**Comment by adangel** [comment]
Thanks for the suggestion. There was no need for that yet, hence there were no plans.

The implementation of this isn't straightforward:
* pt-osc only takes the part after "ALTER TABLE ...". That means, we'd need to verify, that your sql statement is a ALTER TABLE statement starting with ALTER TABLE and parse the table name out of it.
* The [sql change](https://docs.liquibase.com/change-types/community/sql.html) supports multiple statements/multiple lines, while pt-osc doesn't. You can however "perform multiple modifications to the table by specifying them with commas." (see [--alter](https://www.percona.com/doc/percona-toolkit/LATEST/pt-online-schema-change.html#cmdoption-pt-online-schema-change-alter)) - that only works for the same table. If there are multiple alter table statements with different tables, we probably would need to execute pt-osc multiple times? Since any of the executions could fail, you could end up in a inconsistent state (a changeset only partially applied).

So I guess, it could be implemented with certain restrictions and the behavior should be well-defined (e.g. when the statement is not a ALTER TABLE statement, or when there are multiple ALTER TABLE statements).

You've used as a table name in your example "{table}". This doesn't look like a real table name, more like a variable. I'm not aware, that liquibase supports this. Is this a feature of liquibase?

**Comment by adangel** [comment]
> You've used as a table name in your example "{table}". This doesn't look like a real table name, more like a variable. I'm not aware, that liquibase supports this. Is this a feature of liquibase?

This seems to be a changelog property: https://docs.liquibase.com/concepts/basic/changelog-property-substitution.html
Although it should read then `${table}` (with the dollar sign)....

**Comment by JayneCobbTCS** [comment]
We are attempting to convert table character sets from `latin1` to `utf8mb4`. Is there a way to accomplish this with the Liquibase Percona plugin today?  If not, we could use the feature outlined above:

```
databaseChangeLog:
- changeSet:
    id: convert-charset
    author: antbody
    changes:
    - sql:
        usePercona: true
        splitStatements: true
        sql: |
            ALTER TABLE foo_table CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8_unicode_ci;
```
